apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: devops-lab
data:
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "app"
  APP_ENV: "dev"
