apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-prune-test
  labels:
    app.kubernetes.io/name: devops-platform
    app.kubernetes.io/component: gitops-test
    app.kubernetes.io/managed-by: Helm
data:
  purpose: "safe prune test"
