{{- if and .Values.postgres.enabled .Values.postgres.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.postgres.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "devops-platform.componentLabels" (dict "root" . "component" "postgres") | nindent 4 }}
automountServiceAccountToken: {{ .Values.postgres.serviceAccount.automountServiceAccountToken }}
{{- end }}
