map $http_x_request_id $req_id {
    default $http_x_request_id;
    ""      $request_id;
}

log_format main_json escape=json
  '{"timestamp":"$time_iso8601",'
  '"level":"info",'
  '"service":"frontend",'
  '"event":"http_request",'
  '"request_id":"$req_id",'
  '"method":"$request_method",'
  '"path":"$uri",'
  '"status":$status,'
  '"bytes_sent":$bytes_sent,'
  '"duration_s":$request_time,'
  '"remote_addr":"$remote_addr",'
  '"upstream_addr":"$upstream_addr",'
  '"upstream_status":"$upstream_status",'
  '"user_agent":"$http_user_agent"}';

server {
    listen 8080;

    root /usr/share/nginx/html;
    index index.html;

    access_log /dev/stdout main_json;
    error_log /dev/stderr warn;

    client_body_temp_path /tmp/client_temp;
    proxy_temp_path /tmp/proxy_temp;
    fastcgi_temp_path /tmp/fastcgi_temp;
    uwsgi_temp_path /tmp/uwsgi_temp;
    scgi_temp_path /tmp/scgi_temp;

    location /api {
        proxy_set_header X-Request-ID $req_id;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_pass http://backend:5000/;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
