{{- if and .Values.backend.enabled .Values.backend.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.backend.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "devops-platform.componentLabels" (dict "root" . "component" "backend") | nindent 4 }}
automountServiceAccountToken: {{ .Values.backend.serviceAccount.automountServiceAccountToken }}
{{- end }}
