apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: devops-lab

spec:
  replicas: 1

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      serviceAccountName: postgres-sa
      automountServiceAccountToken: false

      securityContext:
        fsGroup: 70
        fsGroupChangePolicy: OnRootMismatch

      initContainers:
        - name: postgres-volume-permissions
          image: postgres:16-alpine
          command:
            - sh
            - -c
            - |
              mkdir -p /var/lib/postgresql/data /var/run/postgresql /tmp
              chown -R 70:70 /var/lib/postgresql/data /var/run/postgresql /tmp
              chmod 700 /var/lib/postgresql/data
              chmod 3775 /var/run/postgresql
              chmod 1777 /tmp
          securityContext:
            runAsUser: 0
            allowPrivilegeEscalation: false
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: postgres-run
              mountPath: /var/run/postgresql
            - name: tmp
              mountPath: /tmp

      containers:
        - name: postgres
          image: postgres:16-alpine
          imagePullPolicy: IfNotPresent

          securityContext:
            runAsNonRoot: true
            runAsUser: 70
            runAsGroup: 70
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

          ports:
            - containerPort: 5432

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: postgres-run
              mountPath: /var/run/postgresql
            - name: tmp
              mountPath: /tmp

      volumes:
        - name: postgres-data
          emptyDir: {}
        - name: postgres-run
          emptyDir: {}
        - name: tmp
          emptyDir: {}
