{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "devops-platform.componentLabels" (dict "root" . "component" "redis") | nindent 4 }}
  annotations:
    config.linkerd.io/opaque-ports: "6379"
spec:
  type: {{ .Values.redis.service.type }}
  selector:
    app: {{ .Values.redis.labels.app }}
  ports:
    - port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.service.targetPort }}
      protocol: TCP
{{- end }}
