{{- if and .Values.redis.enabled .Values.redis.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.redis.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "devops-platform.componentLabels" (dict "root" . "component" "redis") | nindent 4 }}
automountServiceAccountToken: {{ .Values.redis.serviceAccount.automountServiceAccountToken }}
{{- end }}
