apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: devops-lab

spec:
  replicas: 1

  selector:
    matchLabels:
      app: redis

  template:
    metadata:
      labels:
        app: redis

    spec:
      serviceAccountName: redis-sa
      automountServiceAccountToken: false

      securityContext:
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

      containers:
        - name: redis
          image: redis:7-alpine
          imagePullPolicy: IfNotPresent

          securityContext:
            runAsNonRoot: true
            runAsUser: 999
            runAsGroup: 1000
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

          ports:
            - containerPort: 6379

          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"

          volumeMounts:
            - name: redis-data
              mountPath: /data
            - name: tmp
              mountPath: /tmp

      volumes:
        - name: redis-data
          emptyDir: {}
        - name: tmp
          emptyDir: {}
